import Head from 'next/head';
import { Layout } from 'antd';
import mainStyle from '../styles/main.module.css';

export default function BaseLayout({
  children
}: {
  children: React.ReactNode
}) {
  const { Header, Content } = Layout;
  return (
    <>
      <Head>
        <title>Covid Chart</title>
        <meta name="description" content="Generated by KKK" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Header className={mainStyle.header}>
            <h1>App title</h1>
          </Header>
          <Content>{children}</Content>
        </Layout>
      </main>
    </>
  )
}
